services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redisdata:/data

  mercatify_backend:
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env
    depends_on:
      - redis
    command: ["./command.sh"]
  
  db:
    image: postgres:15
    container_name: mercatify_psql
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mercatify_backend
    volumes:
      - pgdata:/var/lib/postgres/data
    ports:
      - 5433:5432

volumes:
  redisdata:
  pgdata:
